[package]
name = "libseat"
description = "Safe libseat bindings"
version = "0.1.0"
authors = [
  "Poly <marynczak.bartlomiej@gmail.com>",
  "MaxVerevkin <maxxverrr@gmail.com>",
]
edition = "2021"

keywords = ["libseat"]
license = "MIT"

[dependencies]
libseat-sys = { version = "0.1.7" }
